{"uuid": "d4e33e6b-fde3-4b35-a107-b4b3a8c76f76", "children": ["9837afa6-eefa-4e4e-a119-8966d14579ba"], "befores": [{"name": "lf_tools", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/ctpriv-scripts/altice/wlan-testing/tests/conftest.py\", line 762, in lf_tools\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../libs/lanforge/lf_tools.py\", line 201, in __init__\n    self.staConnect = StaConnect2(self.lanforge_ip, self.lanforge_port, debug_=self.debug)\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../lanforge/lanforge-scripts/py-scripts/sta_connect2.py\", line 56, in __init__\n    super().__init__(host, port, debug_=debug_, _exit_on_fail=_exit_on_fail)\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/lanforge/lanforge-scripts/py-json/realm.py\", line 112, in __init__\n    self.check_connect()\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/lanforge/lanforge-scripts/py-json/LANforge/lfcli_base.py\", line 416, in check_connect\n    time.sleep(2)\n"}, "start": 1696930179764, "stop": 1696930183814}], "start": 1696930179764, "stop": 1696930184168}